// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/// @title IAztecVerifier
/// @notice Interface for verifying zero-knowledge proofs generated by Aztec/Noir circuits
/// @dev This interface allows swapping different verifier implementations:
///      - Noir-generated verifier contracts (e.g., Barretenberg, PLONK verifiers)
///      - Bridge contracts that forward verification to Aztec L2
///      - Mock verifiers for testing
interface IAztecVerifier {
    /// @notice Verify a zero-knowledge proof with public inputs
    /// @dev The proof and public inputs are generated by the Aztec/Noir circuit.
    ///      For the private skill tree use case, publicInputs encodes:
    ///      - user_address (AztecAddress converted to bytes20/address)
    ///      - skill_hash (bytes32)
    ///      - min_level (uint8)
    ///      The exact encoding format should match what the Noir circuit emits.
    /// @param proof The zkSNARK proof bytes produced by the Noir/Aztec circuit
    ///               Format depends on the proof system (e.g., PLONK, Barretenberg)
    /// @param publicInputs Encoded public inputs from the circuit execution.
    ///                     Should contain: [user_address, skill_hash, min_level]
    ///                     Encoding format: abi.encodePacked(user_address, skill_hash, min_level)
    ///                     or similar format agreed between Aztec L2 and L1
    /// @return true if the proof is valid, false otherwise
    function verify(bytes calldata proof, bytes calldata publicInputs)
        external
        returns (bool);
}

