import { ethers } from 'hardhat';
import * as fs from 'fs';
import * as path from 'path';

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log('Deploying contracts with account:', deployer.address);
  console.log('Account balance:', (await ethers.provider.getBalance(deployer.address)).toString());

  const SelfHumanSBT = await ethers.getContractFactory('SelfHumanSBT');
  const selfHumanSBT = await SelfHumanSBT.deploy();
  await selfHumanSBT.waitForDeployment();
  const selfHumanSBTAddress = await selfHumanSBT.getAddress();
  console.log('SelfHumanSBT deployed to:', selfHumanSBTAddress);

  const SkillLeaderboard = await ethers.getContractFactory('SkillLeaderboard');
  const skillLeaderboard = await SkillLeaderboard.deploy(selfHumanSBTAddress);
  await skillLeaderboard.waitForDeployment();
  const skillLeaderboardAddress = await skillLeaderboard.getAddress();
  console.log('SkillLeaderboard deployed to:', skillLeaderboardAddress);

  const network = await ethers.provider.getNetwork();
  const deploymentInfo = {
    network: network.name,
    chainId: Number(network.chainId),
    addresses: {
      SelfHumanSBT: selfHumanSBTAddress,
      SkillLeaderboard: skillLeaderboardAddress,
    },
  };

  const artifactsDir = path.join(__dirname, '../artifacts/contracts');
  const selfHumanSBTArtifact = JSON.parse(
    fs.readFileSync(path.join(artifactsDir, 'SelfHumanSBT.sol/SelfHumanSBT.json'), 'utf8')
  );
  const skillLeaderboardArtifact = JSON.parse(
    fs.readFileSync(path.join(artifactsDir, 'SkillLeaderboard.sol/SkillLeaderboard.json'), 'utf8')
  );

  const contractsTsPath = path.join(__dirname, '../../common/src/contracts.ts');
  const contractsTsContent = `// Auto-generated by deploy script
// Network: ${network.name} (Chain ID: ${network.chainId})

export const SELF_HUMAN_SBT_ADDRESS = '${selfHumanSBTAddress}' as const;
export const SKILL_LEADERBOARD_ADDRESS = '${skillLeaderboardAddress}' as const;

export const SelfHumanSBTAbi = ${JSON.stringify(selfHumanSBTArtifact.abi, null, 2)} as const;

export const SkillLeaderboardAbi = ${JSON.stringify(skillLeaderboardArtifact.abi, null, 2)} as const;
`;

  fs.writeFileSync(contractsTsPath, contractsTsContent);
  console.log('Contracts config written to:', contractsTsPath);

  console.log('\nDeployment complete!');
  console.log('Addresses:', JSON.stringify(deploymentInfo.addresses, null, 2));
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });

