// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import './SelfHumanSBT.sol';
import './interfaces/IAztecVerifier.sol';

/// @title SkillLeaderboard
/// @notice Public v1 leaderboard for skill tiers. Only human-verified users (SBT holders) can submit skill tiers.
/// @dev This is a non-private v1 implementation that will later be extended with ZK/Aztec integrations for privacy.
///      Supports both plain submissions (v1) and ZK proof-based submissions (v2).
contract SkillLeaderboard {
    SelfHumanSBT public immutable selfHumanSBT;
    IAztecVerifier public aztecVerifier;

    mapping(bytes32 => mapping(address => uint8)) public skillTier;

    event SkillRevealed(address indexed user, bytes32 indexed skillHash, uint8 tier);

    constructor(address _selfHumanSBT, address _aztecVerifier) {
        require(_selfHumanSBT != address(0), 'SelfHumanSBT address cannot be zero');
        require(_aztecVerifier != address(0), 'AztecVerifier address cannot be zero');
        selfHumanSBT = SelfHumanSBT(_selfHumanSBT);
        aztecVerifier = IAztecVerifier(_aztecVerifier);
    }

    /// @notice Submit or update a skill tier for the caller (v1 - plain submission)
    /// @dev Only human-verified users (SBT holders) can submit. Latest tier overwrites previous value.
    ///      This is the v1 entrypoint. In a fully private version, only proof-based submissions would be allowed.
    /// @param skillHash Hash of the skill identifier
    /// @param tier Skill tier (1-10)
    function submitSkillTier(bytes32 skillHash, uint8 tier) external {
        require(tier > 0, 'Tier must be greater than 0');
        require(tier <= 10, 'Tier must be at most 10');
        require(selfHumanSBT.hasValidSBT(msg.sender), 'Only human-verified users can submit skill tiers');

        skillTier[skillHash][msg.sender] = tier;
        emit SkillRevealed(msg.sender, skillHash, tier);
    }

    /// @notice Submit a skill tier using a ZK proof from Aztec/Noir circuit (v2 - proof-based)
    /// @dev Verifies a zero-knowledge proof that the user's private skill level >= minLevel.
    ///      The proof is generated by the Aztec private skill tree circuit.
    ///      Public inputs encoding: abi.encode(userAddress, skillHash, minLevel)
    ///      - userAddress: address (20 bytes)
    ///      - skillHash: bytes32 (32 bytes)
    ///      - minLevel: uint8 (1 byte)
    ///      Total: 53 bytes when using abi.encode
    /// @param skillHash Hash of the skill identifier
    /// @param minLevel Minimum level threshold proven in the ZK circuit
    /// @param proof The zkSNARK proof bytes from the Aztec/Noir circuit
    /// @param publicInputs Encoded public inputs: abi.encode(userAddress, skillHash, minLevel)
    function submitSkillTierWithProof(
        bytes32 skillHash,
        uint8 minLevel,
        bytes calldata proof,
        bytes calldata publicInputs
    ) external {
        // Require SBT verification
        require(selfHumanSBT.hasValidSBT(msg.sender), 'Only human-verified users can submit skill tiers');

        // Validate minLevel range
        require(minLevel > 0, 'Min level must be greater than 0');
        require(minLevel <= 10, 'Min level must be at most 10');

        // Verify the ZK proof
        require(aztecVerifier.verify(proof, publicInputs), 'Invalid ZK proof');

        // Decode public inputs
        // Format: abi.encode(userAddress, skillHash, minLevel)
        (address userAddress, bytes32 decodedSkillHash, uint8 decodedMinLevel) = abi.decode(
            publicInputs,
            (address, bytes32, uint8)
        );

        // Validate decoded inputs match function arguments and caller
        require(userAddress == msg.sender, 'Public input user address must match caller');
        require(decodedSkillHash == skillHash, 'Public input skill hash must match function argument');
        require(decodedMinLevel == minLevel, 'Public input min level must match function argument');

        // Set the skill tier to the proven minimum level
        // Note: The proof proves level >= minLevel, so we store minLevel as the tier
        // In a future version, we might allow storing a higher tier if the user provides additional proof
        skillTier[skillHash][msg.sender] = minLevel;
        emit SkillRevealed(msg.sender, skillHash, minLevel);
    }
}

